apiVersion: v1
kind: PersistentVolume
metadata:
  name: index
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: index
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index-claim
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: index
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10G