apiVersion: v1
kind: Service              # 1
metadata:
  name: lab3-back
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 8082         # 3
    protocol: TCP          # 4
    targetPort: 8082         # 5
  selector:                # 6
    app: lab3-back      # 7