
version: '3.1'

services:

  api:
    build:
      context: ./index
      dockerfile: Dockerfile
    image: lab3-back
    container_name: lab3-back-container
    command:  sh -c "gradle bootRun"
    volumes:
      - ./index:/workspace/index
    expose:
      - 8082
    ports:
      - '8082:8082'
  
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

    
